import type { Metadata } from "next";
import "./globals.css";
import SiteTitle from "@/ui/SiteTitle";
import GlobalMenu from "@/ui/GlobalMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative w-screen h-screen">
        <header>
          <div className="p-4 absolute top-0 left-0 flex flex-col gap-4 max-w-4/10">
            <SiteTitle />
            <GlobalMenu />
          </div>
        </header>
        <main className="w-full h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
